# Generated by Django 6.0.1 on 2026-02-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('analysis', 'Анализ Алгоритмов'), ('complex', 'Комплексный Анализ'), ('differential', 'Диференциальные уравнения'), ('numerical', 'Численные методы'), ('physics', 'Физика')], max_length=50, verbose_name='Предмет')),
                ('type', models.CharField(choices=[('theory', 'Теория'), ('practice', 'Практика')], max_length=20, verbose_name='Тип вопроса')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('difficulty', models.IntegerField(blank=True, help_text='Используется только для физики (1-5)', null=True, verbose_name='Уровень сложности (для физики)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['subject', 'type', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='TicketCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('analysis', 'Анализ Алгоритмов'), ('complex', 'Комплексный Анализ'), ('differential', 'Диференциальные уравнения'), ('numerical', 'Численные методы'), ('physics', 'Физика')], max_length=50, unique=True, verbose_name='Предмет')),
                ('last_number', models.IntegerField(default=0, verbose_name='Последний номер билета')),
            ],
            options={
                'verbose_name': 'Счетчик билетов',
                'verbose_name_plural': 'Счетчики билетов',
            },
        ),
    ]
